spring:
  datasource:
    url: 'jdbc:postgresql://localhost/mobile-app-ws'
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      maximumPoolSize: '2'
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
server:
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on_param
    include-exception: false
  servlet:
    context-path: /mobile-app-ws
tokenSecret: jf9i4jgu83nfl0